language: rust
cache: cargo
rust:
  - nightly
  - beta
  - stable

matrix:
  allow_failures:
    - rust: nightly

addons:
  apt:
    sources:
      - kalakris-cmake
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
