FROM japaric/x86_64-unknown-linux-gnu:v0.1.14

RUN apt-get update && \
  apt-get install -y cmake && \
  apt-get install -y libcurl4-openssl-dev && \
  apt-get install -y libelf-dev && \
  apt-get install -y libdw-dev
